version: '3.8'

services:
  finpay-postgres:
    image: postgres:15-alpine
    container_name: finpay-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: finpay_admin
      POSTGRES_PASSWORD: TopSecretPassword123!
      POSTGRES_DB: finpay_core
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finpay-network

  finpay-redis:
    image: redis:7-alpine
    container_name: finpay-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass RedisSecret123!
    volumes:
      - redis_data:/data
    networks:
      - finpay-network

  finpay-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: finpay-rabbitmq
    ports:
      - "5672:5672"   # Port giao tiếp của Microservices
      - "15672:15672" # Web UI quản lý RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: finpay_mq
      RABBITMQ_DEFAULT_PASS: RabbitSecret123!
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - finpay-network

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  finpay-network:
    driver: bridge